name       : perl-file-slurp-tiny
version    : 0.004
release    : 8
source     :
    - http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/File-Slurp-Tiny-0.004.tar.gz : 452995beeabf0e923e65fdc627a725dbb12c9e10c00d8018c16d10ba62757f1e
license    : GPL-2.0
component  : programming.perl
summary    : A simple, sane and efficient file slurper
description: |
    A simple, sane and efficient file slurper
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
